#!/usr/bin/env bash
# This script prints numbers from 1 to 100 with FizzBuzz logic
for i in {1..100}; do ((i%3==0&&i%5==0)) && echo "FizzBuzz" || ((i%3==0)) && echo "Fizz" || ((i%5==0)) && echo "Buzz" || echo "$i"; done
